"""
Super Dice Roll Bot — Telegram dice roller.

Roll syntax:  NdM  |  NdM±X  |  NdM<sel>K  |  NdM<sel>K±X
  sel = kh (keep highest) | kl (keep lowest)
        dh (drop highest) | dl (drop lowest)

Commands: /start, /roll, /stats, /history, /admin, /help
Inline:   @bot 4d6kh3  |  @bot stats  |  @bot stats heroic

Environment variables (all optional except BOT_TOKEN):
  BOT_TOKEN          — Telegram bot token (required)
  ADMIN_USER_IDS     — comma-separated Telegram user IDs with /admin access
  HISTORY_FILE       — path for the persistent history JSON file (default: roll_history.json)
  MAX_HISTORY_USERS  — max users kept in memory (default: 1000)
  LOG_FILE           — path for rotating log file (default: console only)
  LOG_MAX_BYTES      — max log file size in bytes (default: 5242880 = 5 MB)
  LOG_BACKUP_COUNT   — number of log backup files (default: 3)
"""

import asyncio
import contextlib
import json
import os
import pathlib
import re
import random
import logging
from collections import OrderedDict, deque
from dataclasses import dataclass
from datetime import datetime
from logging.handlers import RotatingFileHandler
from uuid import uuid4

from dotenv import load_dotenv
from telegram import (
    Update,
    InlineQueryResultArticle,
    InputTextMessageContent,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
)
from telegram.error import TelegramError
from telegram.ext import (
    Application,
    CommandHandler,
    InlineQueryHandler,
    CallbackQueryHandler,
    ContextTypes,
)

load_dotenv()

# ── Logging setup (console + optional rotating file) ─────────────────────────

_log_handlers: list[logging.Handler] = [logging.StreamHandler()]
_log_file = os.environ.get("LOG_FILE", "").strip()
if _log_file:
    try:
        _log_handlers.append(
            RotatingFileHandler(
                _log_file,
                maxBytes=int(os.environ.get("LOG_MAX_BYTES", str(5 * 1024 * 1024))),
                backupCount=int(os.environ.get("LOG_BACKUP_COUNT", "3")),
                encoding="utf-8",
            )
        )
    except Exception as _exc:
        print(f"Warning: could not set up file logging ({_log_file}): {_exc}")

logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    level=logging.INFO,
    handlers=_log_handlers,
)
logger = logging.getLogger(__name__)

# ── Configuration constants ───────────────────────────────────────────────────
MAX_DICE          = 20      # maximum dice per roll
MAX_SIDES         = 100   # maximum sides per die
STATS_ROLLS       = 6        # ability scores generated by /stats
HISTORY_MAXLEN    = 10       # rolls kept per user (in memory)
MAX_HISTORY_USERS = max(1, int(os.environ.get("MAX_HISTORY_USERS", "1000")))
MAX_MSG_LEN       = 3800     # Telegram hard limit is 4096; leave headroom
MAX_DISPLAY_DICE  = 20       # individual dice shown before "…(+N más)"
MAX_MODIFIER      = 10_000   # maximum absolute value of ±modifier
HISTORY_FILE      = pathlib.Path(os.environ.get("HISTORY_FILE", "roll_history.json"))

# ── LRU user history ──────────────────────────────────────────────────────────
# OrderedDict preserves insertion/access order. _get_history() moves the
# accessed uid to the end (most recently used) and evicts the oldest entry
# if the dict exceeds MAX_HISTORY_USERS. This bounds memory without a DB.
user_history: OrderedDict[int, deque] = OrderedDict()

# Set to datetime.now() in main() so uptime is accurate from first poll
BOT_START_TIME: datetime | None = None

# ── Admin configuration ───────────────────────────────────────────────────────

def _parse_admin_ids() -> frozenset[int]:
    """Parse ADMIN_USER_IDS from env. Ignores empty, whitespace-only, or non-numeric values."""
    raw = os.environ.get("ADMIN_USER_IDS", "")
    ids: set[int] = set()
    for part in raw.split(","):
        part = part.strip()
        if part.isdigit():
            ids.add(int(part))
    return frozenset(ids)

ADMIN_IDS: frozenset[int] = _parse_admin_ids()

# ── Roll regex ────────────────────────────────────────────────────────────────
# Groups: (N)? d (M) (?:(k|d)(h|l)(K))? (?:(±mod))?
ROLL_RE = re.compile(
    r"^(\d+)?d(\d+)(?:([kd])([lh])(\d+))?([+-]\d+)?$",
    re.IGNORECASE,
)

SEL_LABELS = {
    "kh": "mantiene los {n} más altos",
    "kl": "mantiene los {n} más bajos",
    "dh": "descarta los {n} más altos",
    "dl": "descarta los {n} más bajos",
}

# ── Stats presets ─────────────────────────────────────────────────────────────
STATS_PRESETS: dict[str, str] = {
    "standard": "4d6dl1",
    "dnd":      "4d6dl1",
    "classic":  "3d6",
    "3d6":      "3d6",
    "heroic":   "5d6dl2",
    "grim":     "3d6kl2",
}

STATS_PRESET_DESCRIPTIONS: dict[str, str] = {
    "4d6dl1": "estándar D&D — 4d6, descarta el más bajo, suma los 3 mayores",
    "3d6":    "clásico — 3d6 en orden, sin descartar",
    "5d6dl2": "heroico — 5d6, descarta los 2 más bajos, suma los 3 mayores",
    "3d6kl2": "sombrío — 3d6, conserva los 2 más bajos",
}


# ── Data classes ──────────────────────────────────────────────────────────────

@dataclass
class RollSpec:
    num_dice: int
    sides:    int
    sel_mode: str | None    # 'kh' | 'kl' | 'dh' | 'dl' | None
    sel_n:    int | None
    modifier: int
    expr:     str           # normalized label, e.g. "4d6dl1+2"


@dataclass
class RollResult:
    all_rolls: list[int]
    kept:      list[int]    # dice that count toward the total
    dropped:   list[int]    # dice that were set aside
    subtotal:  int          # sum(kept)
    total:     int          # subtotal + modifier


# ── Utility helpers ───────────────────────────────────────────────────────────

def _get_history(uid: int) -> deque:
    """Return the user's history deque, creating it if needed.

    Moves uid to the most-recently-used position (end of OrderedDict) and evicts
    the least-recently-used entry when the dict exceeds MAX_HISTORY_USERS.
    The freshly-accessed uid is always at the end, so popitem(last=False) can
    never evict it.
    """
    if uid not in user_history:
        user_history[uid] = deque(maxlen=HISTORY_MAXLEN)
    user_history.move_to_end(uid)
    while len(user_history) > MAX_HISTORY_USERS:
        user_history.popitem(last=False)
    return user_history[uid]


# ── History persistence ───────────────────────────────────────────────────────

def _load_history() -> None:
    """Load user_history from HISTORY_FILE at startup.

    Missing file → start with empty history (normal on first run).
    Corrupted file → log the error and start fresh without crashing.
    Entries beyond HISTORY_MAXLEN are silently trimmed.
    Non-integer keys and non-string entries are skipped defensively.
    """
    if not HISTORY_FILE.exists():
        return
    try:
        raw = json.loads(HISTORY_FILE.read_text(encoding="utf-8"))
        for uid_str, entries in raw.items():
            if not isinstance(uid_str, str) or not uid_str.isdigit():
                continue
            uid = int(uid_str)
            dq: deque = deque(maxlen=HISTORY_MAXLEN)
            for entry in entries:
                if isinstance(entry, str):
                    dq.append(entry)
            if dq:
                user_history[uid] = dq
        logger.info("History loaded: %d user(s) from %s", len(user_history), HISTORY_FILE)
    except json.JSONDecodeError as exc:
        logger.error("History file corrupted, starting with empty history: %s", exc)
    except Exception as exc:
        logger.error("Could not load history from %s: %s", HISTORY_FILE, exc)


def _save_history_to_disk(snapshot: dict) -> None:
    """Write a pre-built snapshot atomically to HISTORY_FILE.

    Strategy: write to a .tmp sidecar first, then os.replace() which is
    atomic on POSIX (rename syscall) and on Windows when src/dst share the
    same drive. A crash mid-write at worst leaves a stale .tmp file; the
    main file is never partially written or truncated.
    """
    tmp = HISTORY_FILE.with_suffix(".tmp")
    try:
        tmp.write_text(json.dumps(snapshot, ensure_ascii=False), encoding="utf-8")
        os.replace(tmp, HISTORY_FILE)
    except Exception as exc:
        logger.error("Failed to save history: %s", exc)
        with contextlib.suppress(Exception):
            tmp.unlink()


async def _do_save(snapshot: dict) -> None:
    """Run the blocking disk write in a thread-pool executor."""
    loop = asyncio.get_event_loop()
    await loop.run_in_executor(None, _save_history_to_disk, snapshot)


def _schedule_history_save() -> None:
    """Snapshot user_history and schedule an async disk write. Non-blocking.

    The snapshot is built synchronously (no races with the asyncio event
    loop) and then handed off to a background Task so the caller returns
    immediately without waiting for disk I/O.
    """
    snapshot = {str(uid): list(dq) for uid, dq in user_history.items()}
    asyncio.create_task(_do_save(snapshot))


def _format_uptime() -> str:
    """Return a human-readable uptime string (hours + minutes, or minutes + seconds)."""
    if BOT_START_TIME is None:
        return "desconocido"
    delta = datetime.now() - BOT_START_TIME
    total_s = int(delta.total_seconds())
    hours, rem = divmod(total_s, 3600)
    minutes, seconds = divmod(rem, 60)
    if hours > 0:
        return f"{hours}h {minutes}m"
    return f"{minutes}m {seconds}s"


def _truncate_dice_list(rolls: list[int], sep: str = " · ") -> str:
    """Show up to MAX_DISPLAY_DICE values; summarize the rest to keep messages short."""
    if len(rolls) <= MAX_DISPLAY_DICE:
        return sep.join(str(r) for r in rolls)
    shown = sep.join(str(r) for r in rolls[:MAX_DISPLAY_DICE])
    return f"{shown} … (+{len(rolls) - MAX_DISPLAY_DICE} más)"


def _roll_annotation(spec: RollSpec, result: RollResult) -> str:
    """Return a celebration/warning string for notable single-die plain rolls."""
    if spec.num_dice == 1 and spec.sel_mode is None and spec.modifier == 0:
        if result.total == spec.sides:
            return " 🎯 *¡Crítico!*"
        if result.total == 1:
            return " 💀 *¡Pifia!*"
    return ""


async def safe_reply(message, text: str, **kwargs) -> None:
    """Send a reply with a hard length cap and TelegramError handling.

    Prevents BadRequest crashes when dice expressions produce very long output.
    If the first attempt fails (e.g. malformed Markdown), retries without
    parse_mode so the user still receives the message as plain text.
    """
    if len(text) > MAX_MSG_LEN:
        text = (
            text[:MAX_MSG_LEN - 100]
            + "\n\n_(Respuesta truncada — usa menos dados para ver el detalle completo)_"
        )
    try:
        await message.reply_text(text, **kwargs)
    except TelegramError as exc:
        logger.error("Failed to send reply: %s", exc)
        if "parse_mode" in kwargs:
            fallback = {k: v for k, v in kwargs.items() if k not in ("parse_mode", "reply_markup")}
            try:
                await message.reply_text(text, **fallback)
            except TelegramError:
                pass


def _is_private(update: Update) -> bool:
    """Return True when the update originates from a private chat."""
    return bool(update.effective_chat and update.effective_chat.type == "private")


# ── Core roll logic ───────────────────────────────────────────────────────────

def parse_roll(raw: str) -> RollSpec:
    m = ROLL_RE.match(raw.strip())
    if not m:
        # Sanitize the raw input before embedding it in a Markdown message
        # to prevent format glitches when the user types backticks or asterisks.
        safe = raw.strip()[:50].replace("`", "'").replace("*", "").replace("_", "")
        raise ValueError(
            f"No entiendo `{safe}`.\n"
            "Formato: `NdM`, `NdM±X`, `NdMkhK`, `NdMdlK±X`\n"
            "Ejemplos: `3d6`, `2d20+3`, `4d6kh3`, `6d8dh2-1`"
        )

    num_dice  = int(m.group(1)) if m.group(1) else 1
    sides     = int(m.group(2))
    op        = m.group(3).lower() if m.group(3) else None
    direction = m.group(4).lower() if m.group(4) else None
    sel_n     = int(m.group(5)) if m.group(5) else None
    modifier  = int(m.group(6)) if m.group(6) else 0

    if not (1 <= num_dice <= MAX_DICE):
        raise ValueError(f"El número de dados debe estar entre 1 y {MAX_DICE}.")
    if not (2 <= sides <= MAX_SIDES):
        raise ValueError(f"Las caras del dado deben estar entre 2 y {MAX_SIDES:,}.")

    sel_mode = f"{op}{direction}" if op else None

    if sel_n is not None:
        if sel_n < 1:
            raise ValueError("El selector debe afectar al menos 1 dado.")
        if sel_n >= num_dice:
            raise ValueError(
                f"No puedes usar {sel_mode}{sel_n} con solo {num_dice} dados: "
                f"el selector debe afectar menos dados que el total."
            )

    if abs(modifier) > MAX_MODIFIER:
        raise ValueError(
            f"El modificador debe estar entre -{MAX_MODIFIER:,} y +{MAX_MODIFIER:,}."
        )

    mod_str = (f"+{modifier}" if modifier > 0 else str(modifier)) if modifier else ""
    sel_str = f"{sel_mode}{sel_n}" if sel_mode else ""
    expr    = f"{num_dice}d{sides}{sel_str}{mod_str}"

    return RollSpec(num_dice, sides, sel_mode, sel_n, modifier, expr)


def execute_roll(spec: RollSpec) -> RollResult:
    all_rolls = [random.randint(1, spec.sides) for _ in range(spec.num_dice)]

    if spec.sel_mode is None:
        kept, dropped = all_rolls[:], []
    else:
        n    = len(all_rolls)
        asc  = sorted(range(n), key=lambda i: all_rolls[i])
        desc = sorted(range(n), key=lambda i: all_rolls[i], reverse=True)

        if   spec.sel_mode == "kh": kept_idx = set(desc[: spec.sel_n])
        elif spec.sel_mode == "kl": kept_idx = set(asc[: spec.sel_n])
        elif spec.sel_mode == "dh": kept_idx = set(desc[spec.sel_n :])
        else:                       kept_idx = set(asc[spec.sel_n :])   # dl

        kept    = [v for i, v in enumerate(all_rolls) if i in kept_idx]
        dropped = [v for i, v in enumerate(all_rolls) if i not in kept_idx]

    subtotal = sum(kept)
    total    = subtotal + spec.modifier
    return RollResult(all_rolls, kept, dropped, subtotal, total)


def format_result(spec: RollSpec, result: RollResult) -> str:
    sign = (
        f" + {spec.modifier}"      if spec.modifier > 0 else
        f" - {abs(spec.modifier)}" if spec.modifier < 0 else ""
    )
    annot = _roll_annotation(spec, result)
    lines = [f"🎲 *{spec.expr}*"]

    if spec.sel_mode is None:
        if spec.num_dice == 1:
            if spec.modifier == 0:
                # "Total: X" is redundant when there's a single die and no modifier
                lines.append(f"└ *Resultado: {result.total}*{annot}")
            else:
                lines.append(f"┌ Resultado: *{result.all_rolls[0]}*{sign}")
                lines.append(f"└ *Total: {result.total}*{annot}")
        else:
            dice_str = _truncate_dice_list(result.all_rolls, " + ")
            lines.append(f"┌ Dados:     [ {dice_str} ]{sign}")
            lines.append(f"└ *Total: {result.total}*{annot}")
    else:
        human    = SEL_LABELS[spec.sel_mode].format(n=spec.sel_n)
        all_str  = _truncate_dice_list(result.all_rolls)
        kept_str = " + ".join(str(r) for r in sorted(result.kept, reverse=True))
        drop_str = _truncate_dice_list(result.dropped)

        lines.append(f"┌ Todos:      [ {all_str} ]")
        if spec.sel_mode.startswith("k"):
            lines.append(
                f"├ ✅ {spec.sel_mode}{spec.sel_n} ({human}): "
                f"[ {kept_str} ] = {result.subtotal}"
            )
            if result.dropped:
                lines.append(f"├ ❌ Descarta: [ {drop_str} ]")
        else:
            lines.append(
                f"├ ❌ {spec.sel_mode}{spec.sel_n} ({human}): [ {drop_str} ]"
            )
            lines.append(f"├ ✅ Mantiene: [ {kept_str} ] = {result.subtotal}")

        if spec.modifier:
            lines.append(f"├ Modificador:{sign}")
        lines.append(f"└ *Total: {result.total}*{annot}")

    return "\n".join(lines)


def history_line(spec: RollSpec, result: RollResult) -> str:
    return f"{spec.expr} → {result.total}"


# ── Stats logic ───────────────────────────────────────────────────────────────

def parse_stats_variant(raw: str | None) -> RollSpec:
    if not raw:
        raw = "standard"
    expr = STATS_PRESETS.get(raw.lower(), raw)
    try:
        return parse_roll(expr)
    except ValueError:
        known = ", ".join(f"`{k}`" for k in STATS_PRESETS)
        raise ValueError(
            f"Variante desconocida: `{raw}`.\n"
            f"Presets disponibles: {known}\n"
            f"O usa una expresión válida como `4d6dl1`, `3d6`, `5d6dl2`."
        )


def format_stats_line(n: int, result: RollResult) -> str:
    all_str = _truncate_dice_list(result.all_rolls)
    if result.dropped:
        drop_str = _truncate_dice_list(result.dropped, ", ")
        return f"Tirada {n}: [ {all_str} ] ❌ [{drop_str}] → *{result.total}*"
    return f"Tirada {n}: [ {all_str} ] → *{result.total}*"


def format_stats(spec: RollSpec, rolls: list[RollResult]) -> str:
    totals  = [r.total for r in rolls]
    desc    = STATS_PRESET_DESCRIPTIONS.get(spec.expr, spec.expr)
    total_s = sum(totals)

    lines = [
        "⚔️ *Estadísticas de D&D*",
        f"_Variante: `{spec.expr}` — {desc}_",
        "",
    ]
    for i, result in enumerate(rolls, 1):
        lines.append(format_stats_line(i, result))
    lines += [
        "",
        f"📊 *Resultados: {', '.join(str(t) for t in totals)}*",
        f"Suma: {total_s} | Promedio: {total_s / len(totals):.1f}",
    ]
    return "\n".join(lines)


def stats_history_line(spec: RollSpec, rolls: list[RollResult]) -> str:
    return f"stats({spec.expr}) → [{', '.join(str(r.total) for r in rolls)}]"


# ── Text constants ────────────────────────────────────────────────────────────

START_TEXT = (
    "👋 ¡Hola! Soy el *Super Dice Roll Bot* 🎲\n\n"
    "Soy un lanzador de dados para D&D y otros juegos de rol.\n\n"
    "Para empezar:\n"
    "  • Escribe `/roll 3d6` para lanzar dados\n"
    "  • Escribe `/stats` para generar estadísticas D&D\n\n"
    "Escribe `/help` para ver todos los comandos y opciones."
)

HELP_TEXT = (
    "🎲 *Super Dice Roll Bot* — Ayuda\n\n"
    "━━━ `/roll NdM[selector][±X]` ━━━\n\n"
    "  `N` — número de dados _(defecto: 1)_\n"
    "  `M` — caras del dado\n\n"
    "  Selectores:\n"
    "  `khK` — keep highest — conserva los K más altos\n"
    "  `klK` — keep lowest  — conserva los K más bajos\n"
    "  `dhK` — drop highest — descarta los K más altos\n"
    "  `dlK` — drop lowest  — descarta los K más bajos\n\n"
    "  Ejemplos:\n"
    "  `/roll 3d6` · `/roll d20+5` · `/roll 4d6dl1`\n"
    "  `/roll 2d20kh1` · `/roll 6d8dh2` · `/roll 5d10kl2-1`\n\n"
    "━━━ `/stats [variante]` ━━━\n\n"
    "  Genera 6 puntuaciones de habilidad D&D.\n"
    "  _Regla estándar: 4d6, descarta el más bajo,_\n"
    "  _suma los 3 mayores — repite 6 veces._\n\n"
    "  `standard` / `dnd` — 4d6dl1 _(por defecto)_\n"
    "  `classic`  / `3d6` — 3d6 en orden\n"
    "  `heroic`            — 5d6dl2\n"
    "  `grim`              — 3d6kl2\n"
    "  O cualquier expresión: `/stats 4d6kh3`\n\n"
    "━━━ Otros comandos ━━━\n\n"
    "  `/history` — tus últimos lanzamientos\n"
    "  `/help`    — esta ayuda\n\n"
    "━━━ Modo inline ━━━\n\n"
    "  `@NombreDelBot 4d6dl1`       — prepara un lanzamiento\n"
    "  `@NombreDelBot stats`        — prepara stats estándar\n"
    "  `@NombreDelBot stats heroic` — prepara variante heroica\n\n"
    "_El mensaje inline no muestra ningún número: pulsa el botón_\n"
    "_🎲 Revelar en el chat para generar y mostrar el resultado real._"
)


# ── Global error handler ──────────────────────────────────────────────────────

async def error_handler(update: object, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Catch unhandled exceptions, log them, and send a generic reply when possible."""
    logger.error("Unhandled exception in handler", exc_info=context.error)
    if isinstance(update, Update) and update.effective_message:
        try:
            await update.effective_message.reply_text(
                "⚠️ Ocurrió un error inesperado. Por favor intenta de nuevo.\n"
                "Si el problema persiste, escribe `/help`."
            )
        except TelegramError:
            pass  # nothing else we can do


# ── Command handlers ──────────────────────────────────────────────────────────

async def cmd_start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Friendly first-contact message, separate from the full /help text."""
    if not update.effective_user:
        return
    await safe_reply(
        update.message,
        START_TEXT,
        parse_mode="Markdown",
    )


async def cmd_help(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.effective_user:
        return
    await safe_reply(
        update.message,
        HELP_TEXT,
        parse_mode="Markdown",
    )


async def cmd_roll(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.effective_user:
        return
    if not context.args:
        await safe_reply(
            update.message,
            "❌ Uso: `/roll <expresión>`\nEjemplo: `/roll 4d6dl1`\n"
            "Escribe `/help` para ver todas las opciones.",
            parse_mode="Markdown",
        )
        return

    try:
        spec = parse_roll(context.args[0])
    except ValueError as e:
        await safe_reply(
            update.message,
            f"❌ {e}\n\nEscribe `/help` para ver la sintaxis.",
            parse_mode="Markdown",
        )
        return

    result = execute_roll(spec)
    _get_history(update.effective_user.id).append(history_line(spec, result))
    _schedule_history_save()
    await safe_reply(update.message, format_result(spec, result), parse_mode="Markdown")


async def cmd_stats(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.effective_user:
        return
    raw_variant = context.args[0] if context.args else None

    try:
        spec = parse_stats_variant(raw_variant)
    except ValueError as e:
        await safe_reply(
            update.message,
            f"❌ {e}\n\nEscribe `/help` para ver las variantes disponibles.",
            parse_mode="Markdown",
        )
        return

    rolls = [execute_roll(spec) for _ in range(STATS_ROLLS)]
    _get_history(update.effective_user.id).append(stats_history_line(spec, rolls))
    _schedule_history_save()
    await safe_reply(update.message, format_stats(spec, rolls), parse_mode="Markdown")


async def cmd_history(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.effective_user:
        return
    history = list(_get_history(update.effective_user.id))
    if not history:
        hint = "Usa `/roll 3d6` o `/stats` para empezar."
        await safe_reply(
            update.message,
            f"📋 No tienes lanzamientos registrados aún.\n{hint}",
            parse_mode="Markdown",
        )
        return

    lines = [f"{i + 1}. {e}" for i, e in enumerate(reversed(history))]
    await safe_reply(
        update.message,
        "📋 *Tus últimos lanzamientos:*\n\n" + "\n".join(lines),
        parse_mode="Markdown",
    )


async def cmd_admin(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Read-only admin panel. Access controlled by ADMIN_USER_IDS in .env."""
    if not update.effective_user:
        return

    if not _is_private(update):
        await safe_reply(update.message, "ℹ️ Este comando solo está disponible en chat privado.")
        return

    if not ADMIN_IDS:
        await safe_reply(
            update.message,
            "ℹ️ El panel de administración no está configurado.\n"
            "Añade `ADMIN_USER_IDS` a `.env` para activar este comando.",
        )
        return

    if update.effective_user.id not in ADMIN_IDS:
        await safe_reply(update.message, "⛔ No tienes permiso para usar este comando.")
        logger.warning("Unauthorized /admin attempt by user %d", update.effective_user.id)
        return

    text = (
        "🔧 *Panel de administración*\n\n"
        f"⏱ Uptime: `{_format_uptime()}`\n"
        f"👥 Usuarios en memoria: `{len(user_history)}` / `{MAX_HISTORY_USERS}`\n"
        f"📋 Profundidad de historial: últimas `{HISTORY_MAXLEN}` tiradas por usuario\n"
        f"🎲 Dados máximos por tirada: `{MAX_DICE}`\n"
        f"🔑 Admins configurados: `{len(ADMIN_IDS)}`\n\n"
        "📦 Comandos: /roll · /stats · /history · /help · /start · /admin"
    )
    await safe_reply(update.message, text, parse_mode="Markdown")


# ── Inline handler ────────────────────────────────────────────────────────────
#
# Security note — inline never bakes a real roll into the message content:
# Telegram lets a client turn any inline result into a *scheduled* message,
# but neither InlineQuery nor ChosenInlineResult carry any field indicating
# that, or when the message will actually be sent. A result's content is
# fixed at answer time and delivered verbatim whenever the client sends it —
# immediately or hours later. If inline computed the roll up front, a player
# could inline-roll repeatedly until a favorable result appeared, then
# schedule that exact message to be delivered later as if it were live.
#
# Fix: inline results carry no dice numbers at all — only a "reveal" button
# (reply_markup). Selecting a result with reply_markup makes Telegram assign
# the sent message an inline_message_id once it is actually delivered to a
# chat (this is the same mechanism Telegram's own inline games use to update
# scores after the fact). execute_roll() only runs inside
# inline_reveal_callback(), triggered by a real tap on that live message —
# which cannot happen before the message exists in the chat, so a scheduled
# message still shows nothing but the pending placeholder until someone
# taps it live. The button is removed after one reveal so the result can't
# be rerolled.

def _pending_roll_text(expr: str) -> str:
    return f"🎲 *{expr}*\n└ _Pulsa el botón para revelar el resultado_"


def _pending_stats_text(expr: str) -> str:
    return f"⚔️ *Stats D&D ({expr})*\n_Pulsa el botón para revelar las estadísticas_"


def _reveal_keyboard(payload: str) -> InlineKeyboardMarkup:
    return InlineKeyboardMarkup([[InlineKeyboardButton("🎲 Revelar", callback_data=payload)]])


async def inline_query(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    query = update.inline_query.query.strip()

    if not query:
        d20_spec   = parse_roll("1d20")
        stats_spec = parse_stats_variant(None)

        hints = [
            InlineQueryResultArticle(
                id=str(uuid4()),
                title="🎲 Preparar 1d20",
                description="Toca para insertar · el resultado se revela al pulsar el botón en el chat",
                input_message_content=InputTextMessageContent(
                    _pending_roll_text(d20_spec.expr), parse_mode="Markdown"
                ),
                reply_markup=_reveal_keyboard(f"r:{d20_spec.expr}"),
            ),
            InlineQueryResultArticle(
                id=str(uuid4()),
                title="⚔️ Preparar stats D&D (4d6dl1)",
                description="Toca para insertar · las estadísticas se revelan al pulsar el botón",
                input_message_content=InputTextMessageContent(
                    _pending_stats_text(stats_spec.expr), parse_mode="Markdown"
                ),
                reply_markup=_reveal_keyboard(f"s:{stats_spec.expr}"),
            ),
        ]
        await update.inline_query.answer(hints, cache_time=0)
        return

    # ── Stats branch ──────────────────────────────────────────────────────────
    if query.lower().startswith("stats"):
        parts       = query.split(maxsplit=1)
        raw_variant = parts[1] if len(parts) > 1 else None

        try:
            spec = parse_stats_variant(raw_variant)
        except ValueError:
            err = InlineQueryResultArticle(
                id=str(uuid4()),
                title="❌ Variante inválida — no enviar",
                description="Corrige la expresión · Prueba: stats · stats heroic · stats 4d6dl1",
                input_message_content=InputTextMessageContent(
                    "❌ Variante inválida. Escribe `/help` en el bot para ver las opciones.",
                ),
            )
            await update.inline_query.answer([err], cache_time=0)
            return

        answer = InlineQueryResultArticle(
            id=str(uuid4()),
            title=f"⚔️ Preparar stats D&D ({spec.expr})",
            description="Toca para insertar · se revela al pulsar el botón en el chat",
            input_message_content=InputTextMessageContent(
                _pending_stats_text(spec.expr), parse_mode="Markdown"
            ),
            reply_markup=_reveal_keyboard(f"s:{spec.expr}"),
        )
        await update.inline_query.answer([answer], cache_time=0)
        return

    # ── Roll branch ───────────────────────────────────────────────────────────
    try:
        spec = parse_roll(query)
    except ValueError:
        err = InlineQueryResultArticle(
            id=str(uuid4()),
            title="❌ Expresión inválida — no enviar",
            description="Corrige antes de tocar · Prueba: 3d6 · 4d6dl1 · 2d20kh1+3",
            input_message_content=InputTextMessageContent(
                "❌ Expresión inválida. Escribe `/help` en el bot para ver la sintaxis.",
            ),
        )
        await update.inline_query.answer([err], cache_time=0)
        return

    answer = InlineQueryResultArticle(
        id=str(uuid4()),
        title=f"🎲 Preparar {spec.expr}",
        description="Toca para insertar · se revela al pulsar el botón en el chat",
        input_message_content=InputTextMessageContent(
            _pending_roll_text(spec.expr), parse_mode="Markdown"
        ),
        reply_markup=_reveal_keyboard(f"r:{spec.expr}"),
    )
    await update.inline_query.answer([answer], cache_time=0)


# ── Inline reveal callback ────────────────────────────────────────────────────

async def inline_reveal_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Compute and reveal the real roll only when the button is actually tapped.

    Runs at the moment of live interaction on a message that already exists
    in a chat — whether it was sent immediately or delivered later as a
    scheduled message, no roll exists until this handler executes. The
    button is removed after reveal, so a result can't be rerolled.
    """
    query = update.callback_query
    kind, _, payload = (query.data or "").partition(":")

    try:
        if kind == "r":
            spec   = parse_roll(payload)
            result = execute_roll(spec)
            text   = format_result(spec, result)
        elif kind == "s":
            spec  = parse_stats_variant(payload)
            rolls = [execute_roll(spec) for _ in range(STATS_ROLLS)]
            text  = format_stats(spec, rolls)
        else:
            await query.answer()
            return
    except ValueError:
        await query.answer("❌ Expresión inválida.", show_alert=True)
        return

    await query.answer()
    try:
        await query.edit_message_text(text, parse_mode="Markdown", reply_markup=None)
    except TelegramError as exc:
        logger.error("Failed to reveal inline roll: %s", exc)


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    global BOT_START_TIME

    token = os.environ.get("BOT_TOKEN")
    if not token:
        raise RuntimeError(
            "Falta BOT_TOKEN.\n"
            "En desarrollo: ponlo en .env → BOT_TOKEN=tu_token\n"
            "En producción: defínelo como variable de entorno del sistema."
        )

    BOT_START_TIME = datetime.now()

    app = Application.builder().token(token).build()

    # Global error handler — catches unhandled exceptions in any handler
    app.add_error_handler(error_handler)

    # Command handlers
    app.add_handler(CommandHandler("start",   cmd_start))
    app.add_handler(CommandHandler("help",    cmd_help))
    app.add_handler(CommandHandler("roll",    cmd_roll))
    app.add_handler(CommandHandler("stats",   cmd_stats))
    app.add_handler(CommandHandler("history", cmd_history))
    app.add_handler(CommandHandler("admin",   cmd_admin))

    # Inline mode — reveal is deferred to a button tap; see security note above inline_query
    app.add_handler(InlineQueryHandler(inline_query))
    app.add_handler(CallbackQueryHandler(inline_reveal_callback, pattern=r"^[rs]:"))

    _load_history()
    logger.info("Bot iniciado. Ctrl+C para detener.")
    app.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()
